name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate stats images
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: jvignesh148
          template: classic
          base: header, activity, community, repositories
          plugin_languages: yes
          plugin_languages_limit: 8
          output_action: commit
          filename: github-stats.svg
